# Copyright DB Netz AG and contributors
# SPDX-License-Identifier: Apache-2.0

name: generate-model-badge

on: push

jobs:
  generate-model-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate model badge
        uses: DSD-DBS/py-capellambse/ci-templates/github/model-complexity-badge@github-ci-template
        with:
          entry_point: ${{ env.ENTRYPOINT }}
          push_model_badge: "false"
    env:
      ENTRYPOINT: "./coffee-machine-demo.aird"
