# Copyright DB Netz AG and contributors
# SPDX-License-Identifier: Apache-2.0

name: generate model badge

on: push

jobs:
  generate-model-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Generate model badge
        run: |
          git fetch
          git reset
          pip install "git+https://github.com/DSD-DBS/py-capellambse.git@$CAPELLAMBSE_REVISION"
          python <<EOF
          import os
          import pathlib
          import capellambse
          model = capellambse.MelodyModel("./coffee-machine-demo.aird")
          pathlib.Path(os.environ["OUTPUT_FILE"]).write_text(model.description_badge)
          EOF
      - name: Push model badge to repository
        run: |
          git add "$OUTPUT_FILE"
          if git diff --cached --exit-code &> /dev/null || [[ "$PUSH_MODEL_BADGE" == 0 ]]; then exit 0; fi
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "$COMMIT_MSG"
          git push -o ci.skip origin "HEAD:$COMMIT_BRANCH"
      - name: Archive model badge in artifacts
        uses: actions/upload-artifact@v3
        with:
          name: model-complexity-badge
          path: ${{ env.OUTPUT_FILE }}
    env:
      OUTPUT_FILE: model-complexity-badge.svg
      COMMIT_MSG: "docs: Update model complexity badge"
      CAPELLAMBSE_REVISION: v0.5.28
      COMMIT_BRANCH: ${{ github.ref_name }}
      PUSH_MODEL_BADGE: 1
