# Copyright DB Netz AG and contributors
# SPDX-License-Identifier: CC0-1.0

name: generate model badge

on: [ push, pull_request ]

jobs:
  generate-model-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Generate model badge
        run: |
          git fetch
          git reset --hard origin/$COMMIT_BRANCH
          pip install "git+https://github.com/DSD-DBS/py-capellambse.git@$CAPELLAMBSE_REVISION"
          python <<EOF
          import os
          import pathlib
          import capellambse

          model = capellambse.MelodyModel("./coffee-machine-demo.aird")
          pathlib.Path(os.environ["OUTPUT_FILE"]).write_text(model.description_badge)
          EOF
      - name: Push model badge to repository
        run: |
          git add "$OUTPUT_FILE"
          if ! git diff --cached --exit-code &> /dev/null; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git commit -m "$COMMIT_MSG"
            #git push -o ci.skip "https://${GIT_USERNAME:?}:${GIT_PASSWORD:?}@${{ github.server_url }}/${{ github.repository }}" "HEAD:${{ github.ref_name }}"
            git push -o ci.skip origin "HEAD:$COMMIT_BRANCH"
          fi
    env:
      OUTPUT_FILE: model-complexity-badge.svg
      COMMIT_MSG: "docs: Add/Modify model complexity badge"
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
      CAPELLAMBSE_REVISION: v0.5.27
      COMMIT_BRANCH: ${{ github.ref_name }}
